# .github/workflows/release.yml
name: Release VMC Reader

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential clang-format valgrind

      - name: Build (release)
        run: make release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vmcreader
          path: vmcreader

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: vmcreader
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
